Add DSL to build grid columns with LitRenderer
mvysny/karibu-dsl pull request #76
Opened 2024-12-23 08:28 UTC by vlipovetskii

https://github.com/mvysny/karibu-dsl/issues/75

2025-01-07 07:13 UTC, mvysny commented
Thank you, awesome work! However, more work is needed:

* Tests
* Documentation
* Update the Example app.

I can write the tests and the documentation for this approach, but maybe you could update the example app? The example app is a Gradle project in `karibu-dsl`, under the folder `example`. It's a Vaadin Beverage Buddy ported to DSL. I'm thinking that you could for example copy the `CategoriesList` view to a new class and then modify it to be rendered as a LitTemplate. You can publish it uunder the path `/categories-lit` and we can then add a new tab to the navigation menu.

2025-01-07 07:14 UTC, mvysny requested changes
This is great, but we need to demo this in the example app, as suggested in the conversation comment.

2025-01-07 08:11 UTC, vlipovetskii commented
Thank you. I will do it.

2025-01-09 17:53 UTC, vlipovetskii commented
> The example app is a Gradle project in `karibu-dsl`, under the folder `example`. It's a Vaadin Beverage Buddy ported to DSL.

I have tried to import the example project into Idea, but failed with the error message.

```
_```
Task 'wrapper' not found in project ':example'.

* Try:
> Run gradle tasks to get a list of available tasks.
> For more on name expansion, please refer to https://docs.gradle.org/8.10/userguide/command_line_interface.html#sec:name_abbreviation in the Gradle documentation.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 380ms
```_

```

2025-01-09 17:54 UTC, mvysny commented
You need to import the entire karibu-dsl into intellij. Then, the example app will show as a module; open it and run Main.java

2025-01-09 18:02 UTC, vlipovetskii commented
> You need to import the entire karibu-dsl into intellij. Then, the example app will show as a module; open it and run Main.java

Thank you! Now it's ok.

2025-01-10 16:42 UTC, vlipovetskii commented
> I'm thinking that you could for example copy the `CategoriesList` view to a new class and then modify it to be rendered as a LitTemplate. You can publish it uunder the path `/categories-lit` and we can then add a new tab to the navigation menu.

Hi !
I have re-implemented componentColumn with Button component using buildLitRenderer. 
Now the code of componentColumn and  column(buildLitRenderer<Category> are close to each other and it's convenient for comparing. 
I propose to leave the single class CategoriesList with two button columns (componentColumn and column(buildLitRenderer<Category>). To distinguish the button columns I think to add grid column headers like setHeader("componentColumn impl.") and  setHeader("column(buildLitRenderer impl."). 
Such an approach will allow us to avoiding duplication of the remaining code in CategoriesList class. But at thesame time it's convenient for developers to see code of both implemenations on the same screen.

Also it's possible to copy your comment over `public fun <T, V : Component?> (@VaadinDsl Grid<T>).componentColumn`
 from Grid.kt
 * *NOTE:* Using [ComponentRenderer] is not as efficient as the
 * built-in renderers or using `LitRenderer`.
and my comment over` public fun <T> (@VaadinDsl Grid<T>).column(renderer: Renderer<T>`,
 from Grid.kt
 * *NOTE:* Using [Renderer] (built-in renderers or `LitRenderer`) is more efficient than [ComponentRenderer]
into CategoriesList in order to highlight the difference. 

What do you think about this ?
If it's ok, I will add headers for grid columns and update PR with latest commits, including example application.

```
![2025-01-10-18-20-29](https://github.com/user-attachments/assets/b1435568-1ea0-45ce-8f10-f30a717a73e7)
```
```
                componentColumn({ cat -> createEditButton(cat) }) {
                    flexGrow = 0; key = "edit"
                }

                column(buildLitRenderer<Category> {

                    val onButtonClick = function("onButtonClick") { category ->
                        edit(category)
                    }

                    templateExpression {

                        button(cssClass("category__edit"), themeVariant(ButtonVariant.LUMO_TERTIARY), click(onButtonClick)) {
                            icon(icon(VaadinIcon.EDIT.create()))
                            +"Edit"
                        }
                    }
                }) {
                    flexGrow = 0; key = "edit-lit"
                }

```

2025-01-11 11:18 UTC, mvysny commented
That sounds good, I agree with your point - this way both solutions would be present side-by-side, for devs to compare. Please go ahead 👍  Even better, the lit template column could serve as a delete button - but I can make this kind of change afterwards myself.

2025-01-11 15:35 UTC, vlipovetskii commented
> That sounds good, I agree with your point - this way both solutions would be present side-by-side, for devs to compare. Please go ahead 👍 Even better, the lit template column could serve as a delete button - but I can make this kind of change afterwards myself.

I updated PR but **CategoriesListTest** failed.
I tried to fix (added data for a new LitRenderer column) to the test, but it still fails.

Please find the error message:
`Grid[<Category>, dataprovider='ListDataProvider<Category>(1 items)', @multi-sort-priority='prepend', @style='flex-grow:1.0'] at 0: expected [Beers, 0, Button[text='Edit', icon='vaadin:edit', @class='category__edit', @theme='tertiary'],  Delete] but got [Beers, 0, Button[text='Edit', icon='vaadin:edit', @class='category__edit', @theme='tertiary'],   Delete ]
`
Expected and actual data are the same, but nevertheless the 
`grid.expectRow(0, "Beers", "0", "Button[text='Edit', icon='vaadin:edit', @class='category__edit', @theme='tertiary']", "Delete")`
raises error.

You can review the complete code in my forked repo: https://github.com/vlipovetskii/karibu-dsl

It's necessary to update [karibu-testing](https://github.com/mvysny/karibu-testing) to support LitRenderer ?

2025-01-12 08:54 UTC, mvysny commented
> But I think, it's still necessary to update [karibu-testing](https://github.com/mvysny/karibu-testing) to support LitRenderer ?

Yup, sounds like a good idea, please feel free to open a feature request at https://github.com/mvysny/karibu-testing/issues and let's brainstorm a good solution.

Regardless, I can see that the tests pass, excellent work! Let me take a look and review the PR, most probably tomorrow.

2025-01-13 15:06 UTC, mvysny commented on example/src/main/kotlin/com/vaadin/starter/beveragebuddy/ui/categories/CategoriesList.kt
> +                        button(cssClass("category__edit"), themeVariant(ButtonVariant.LUMO_TERTIARY), click(onButtonClick)) {
Just thinking: now the Vaadin Component DSL differs quite a lot from the Renderer DSL:

* Component DSL accepts icon and caption as its parameters and configures the CSS class and theme variant in its body, while
* Renderer DSL accepts CSS class and themeVariant as its parameters, and adds icon and label as its contents.

I understand the technical reasons behind that (so that you can construct the html via string), but let's put technicalities aside and ponder on whether it would be better to have those two functions to have the same parameters. Technically it would be possible to add CSS class later on from the component body, say by constructing the HTML using JSoup.

Regardless, the question is: shouldn't these two `button{}` functions to have as similar parameters as possible?

2025-01-14 17:07 UTC, vlipovetskii commented on example/src/main/kotlin/com/vaadin/starter/beveragebuddy/ui/categories/CategoriesList.kt
> +                        button(cssClass("category__edit"), themeVariant(ButtonVariant.LUMO_TERTIARY), click(onButtonClick)) {
Hi!

Please find below side-by-side comparion of 3 approaches:
1. componentColumn. Note: I replaced createEditButton with it's body to make comparions more descriptive.
2. buildLitRenderer with original DSL
3. buildLitRenderer with the DSL, that tries to mimick the button from VaadinComponents.kt
My thougths are below the code.
```
                componentColumn({ cat ->
                    Button("Edit").apply {
                        icon = Icon(VaadinIcon.EDIT)
                        addClassName("category__edit")
                        addThemeVariants(ButtonVariant.LUMO_TERTIARY)
                        onClick { edit(cat) }
                    }
                }) {
                    flexGrow = 0; key = "edit"
                }

                /**
                 * *NOTE:* Using [ComponentRenderer] is not as efficient as the
                 * built-in renderers or using `LitRenderer`.
                 *
                 * *NOTE:* Using [Renderer] (built-in renderers or `LitRenderer`) is more efficient
                 * than [ComponentRenderer]
                 */
                column(buildLitRenderer<Category> {

                    val onButtonClick = function("onButtonClick") { category ->
                        deleteCategory(category)
                    }

                    templateExpression {

                        button(
                            cssClass("category__edit"),
                            themeVariant(ButtonVariant.LUMO_TERTIARY),
                            click(onButtonClick)
                        ) {
                            icon(icon(VaadinIcon.TRASH.create()))
                            +"Delete"
                        }
                    }
                }) {
                    flexGrow = 0; key = "edit-lit"
                }

                column(buildLitRenderer<Category> {

                    val onButtonClick = function("onButtonClick1") { category ->
                        deleteCategory(category)
                    }

                    templateExpression {

                        button("Delete", VaadinIcon.TRASH.create()) {
                            addClassName("category__edit")
                            addThemeVariants(ButtonVariant.LUMO_TERTIARY)
                            click(onButtonClick)
                        }
                    }
                }) {
                    flexGrow = 0; key = "edit-lit-1"
                }

```
1. Both componentColumn and buildLitRenderer with original DSL assign icon in the initialization block unlike button from VaadinComponents.kt.
2. Though I almost mimicked the button from VaadinComponents.kt, but there is a difference:  click(onButtonClick) vs onClick { edit(cat) }. It's impossible to mimick onClick at all. 
3. When I developed the the DSL (and in when I used in my applications) I googled the examples of LitRenderer usage. In fact, the examples are the html text and my original DSL structure close to the html text as much as possible. Such an approach helps to use examples of LitRenderer html text, but create structure using DSL.

**Conclusion**: I propose to leverage the original DSL.

Please note: I will update PR to add

```
public fun <TSource> KLitRendererTagsBuilderA<TSource>.id(value: String) =
    KLitRendererAttribute("id", value)

```

2025-01-15 17:38 UTC, vlipovetskii commented on example/src/main/kotlin/com/vaadin/starter/beveragebuddy/ui/categories/CategoriesList.kt
> +                        button(cssClass("category__edit"), themeVariant(ButtonVariant.LUMO_TERTIARY), click(onButtonClick)) {
I have updated PR with two changes: 
```
public fun <TSource> KLitRendererTagsBuilderA<TSource>.id(value: String) =
    KLitRendererAttribute("id", value)

```
Delegate functions for Property and Function added to generate names from kotlin local variable name automatically.
```
                    /*
                    val onButtonClick = function("onButtonClick") { category ->
                        deleteCategory(category)
                    }
                     */
                    // OR
                    val onButtonClick by function { category ->
                        deleteCategory(category)
                    }

```

2025-01-16 07:08 UTC, mvysny commented on example/src/main/kotlin/com/vaadin/starter/beveragebuddy/ui/categories/CategoriesList.kt
> +                        button(cssClass("category__edit"), themeVariant(ButtonVariant.LUMO_TERTIARY), click(onButtonClick)) {
"3." is a good point, I agree. Let's go with the PR as-is. Sorry for such a delay, let me take a look at the PR again.

2025-01-16 07:20 UTC, mvysny requested changes

2025-01-16 07:20 UTC, mvysny commented on karibu-dsl/src/main/kotlin/com/github/mvysny/karibudsl/v10/KCssVarNameA.kt
> + * style="line-height: var(--lumo-line-height-m);"
I'm not sure what this means; could you please rewrite the kdoc, say: allows you to insert a CSS variable. Intended usage from [xyz] function. Example of the produced variable: xyz.

2025-01-16 07:20 UTC, mvysny commented on karibu-dsl/src/main/kotlin/com/github/mvysny/karibudsl/v10/KLitRendererAttributesDsl.kt
> + * style="align-items: center;"
Same remark as the one above.

2025-01-16 07:20 UTC, mvysny commented on karibu-dsl/src/main/kotlin/com/github/mvysny/karibudsl/v10/KLitRendererAttributesDsl.kt
> + * --- Renderers https://vaadin.com/docs/latest/components/grid/renderers
Could you add an example on how to use this function and what that usage will produce?

2025-01-16 07:20 UTC, mvysny commented on karibu-dsl/src/main/kotlin/com/github/mvysny/karibudsl/v10/KLitRendererDsl.kt
> + * PRB: \${item.itemName} -> isn't interpreted by [LitRenderer]
I'm not sure what this means - could you please rephrase so that users know how to use this function, and what it does?

2025-01-16 07:20 UTC, mvysny commented on karibu-dsl/src/main/kotlin/com/github/mvysny/karibudsl/v10/KLitRendererDsl.kt
> + * --- Renderers https://vaadin.com/docs/latest/components/grid/renderers
Same thing: I'm quite lost as to what this interface is supposed to do, and the current kdoc (which is a list of links) isn't really helping.

2025-01-16 07:20 UTC, mvysny commented on karibu-dsl/src/main/kotlin/com/github/mvysny/karibudsl/v10/KLitRendererTagsDsl.kt
> +     * --- What are Self Closing Tags in HTML? https://www.scaler.com/topics/self-closing-tags-in-html/
It's better to update to something like this: by default, all html tags are closed (e.g. `<br/>` or `<b>foo</b>`; set to false in special cases yada yada, please read more on self-closing tags at http:// foo bar

2025-01-16 07:20 UTC, mvysny commented on karibu-dsl/src/main/kotlin/com/github/mvysny/karibudsl/v10/KLitRendererTagsDsl.kt
> +     * "<img src=${item.image} />"
It's hard to read this kind of kdoc. Better way: Creates an `<img src="..." />` tag. Intended usage: xyz, will output: abc. Note: this tag is self-closing: [selfClosing] is set to true.

Also, please avoid using custom formatting such as `---`: please only use the supported kdoc syntax as present here: https://kotlinlang.org/docs/kotlin-doc.html

2025-01-16 07:20 UTC, mvysny commented on karibu-dsl/src/main/kotlin/com/github/mvysny/karibudsl/v10/KLitRendererTheme.kt
> + * --- Renderers https://vaadin.com/docs/latest/components/grid/renderers
Same here

2025-01-16 07:20 UTC, mvysny commented on karibu-dsl/src/main/kotlin/com/github/mvysny/karibudsl/v10/KLumoColors.kt
> + * --- Lumo Colors https://vaadin.com/docs/latest/styling/lumo/lumo-style-properties/color
Same here

2025-01-16 07:20 UTC, mvysny commented on karibu-dsl/src/main/kotlin/com/github/mvysny/karibudsl/v10/KLumoTypography.kt
> + * --- Lumo Typography https://vaadin.com/docs/latest/styling/lumo/lumo-style-properties/typography
Same here

2025-01-16 17:30 UTC, vlipovetskii commented
Updated PR following the requested changes after code review.

2025-01-17 11:39 UTC, mvysny commented
Wohoo, amazing job with the kdoc, thanks a ton! Let me review the PR one more time and it's merge time :)

2025-01-17 12:01 UTC, mvysny approved these changes

2025-01-17 12:01 UTC, merged

2025-01-17 12:01 UTC, mvysny commented
Amazing work, thank you so much for your contribution 🙏  Now the ball is on my side, let me create a bunch of tests and documentation.